name: Docker Build and Push

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: cicd
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Custom Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/hanhthong/standupnow:${{ github.sha }}-${{ github.run_id }}


      - name: Deploy to ArgoCD
        shell: bash
        run: |
          argocd app set standupnow -p image.tag=${{ github.sha }}-${{ github.run_id }} --auth-token ${{ secrets.ARGOCD_TOKEN }}
